## The location of the Discord IPC path. If not specified, it will be automatically detected.
# discord_ipc_path = "/run/user/1000/discord-ipc-0"

## The remote address that the host will connect and forward packets to.
# remote_address = "192.168.86.31:49131"

## Whether or not to keep the unix socket created by this program on exit. Default value is "false".
# keep_socket = false
